title: Brandon Theard
#logo: /assets/img/headshot_circle.png
description: Data Scientist with a background in Chemistry and expertise in Python, data analysis, and machine learning. Skilled in predictive modeling, visualization, and deriving actionable insights using tools like Pandas, Scikit-Learn, and Tableau. Holds certifications from MIT in Data Science and the Institute of Data, University of Louisiana at Lafayette. Passionate about data-driven decision-making and experienced in research, finance, and analytics. 



show_dowloads: true
theme: jekyll-theme-minimal
